baseURL = "https://lettersfromshiraz.com/"
languageCode = "en-us"
title = "Letters from Shiraz ‚úç"
theme = "paperesque-mainline"

[[params.menu]]
  name = "blog"
  url = "posts/"

[[params.menu]]
  name = "tags"
  url = "tags/"

[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "contact"
  url = "contact/"